name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2

      - name: Generate 3D Profile
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: EdenilsonGitHub

      - name: Commit and push generated files
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add profile-3d-contrib || echo "Nada para adicionar"
          git commit -m "Adiciona gráfico 3D de contribuições gerado automaticamente" || echo "Nada para commitar"
          git push origin main